INSERT INTO user002.dp_re (ID, REFERENCE_DATE, DESCRIPTION, AMOUNT, STATUS)
SELECT
    p.IDENTIFIER,
    p.REFERENCE_DATE,
    'Descrizione fissa',
    p.VALUE,
    'ACTIVE'
FROM
    TSEEUI02.PERIMETRO p
    where p.REFERENCE_DATE= TO_DATE(?,'YYYY-MM-DD')